alert("Hello World");
var a;
var b;
var operator;
var answer;
var a_flag=false;
var b_flag=false;
var operator_flag=false;
$(document).ready(function(){
    $("#1").click(function(){
        if(a_flag===false)
        {
            a=1;
            a_flag=true;
        }
        else
        {
            b_flag===false;
            b=1;
        }
    })
    $("#2").click(function(){
        if(a_flag===false)
        {
            a=2;
            a_flag=true;
        }
        else
        {
            b_flag===false;
            b=2;
        }
    })
    $("#3").click(function(){
        if(a_flag===false)
        {
            a=3;
            a_flag=true;
        }
        else
        {
            b_flag===false;
            b=3;
        }
    })
    $("#4").click(function(){
        if(a_flag===false)
        {
            a=4;
            a_flag=true;
        }
        else
        {
            b_flag===false;
            b=4;
        }
    })
    $("#5").click(function(){
        if(a_flag===false)
        {
            a=5;
            a_flag=true;
        }
        else
        {
            b_flag===false;
            b=5;
        }
    })
    $("#6").click(function(){
        if(a_flag===false)
        {
            a=6;
            a_flag=true;
        }
        else
        {
            b_flag===false;
            b=6;
        }
    })
    $("#7").click(function(){
        if(a_flag===false)
        {
            a=7;
            a_flag=true;
        }
        else
        {
            b_flag===false;
            b=7;
        }
    })
    $("#8").click(function(){
        if(a_flag===false)
        {
            a=8;
            a_flag=true;
        }
        else
        {
            b_flag===false;
            b=8;
        }
    })
    $("#9").click(function(){
        if(a_flag===false)
        {
            a=9;
            a_flag=true;
        }
        else
        {
            b_flag===false;
            b=9;
        }
    })
    $('#0').click(function(){
        if(a_flag===false)
        {
            a=0;
            a_flag=true;
        }
        else
        {
            b_flag=true;
            b=0;
        }
    })
    $("#plus").click(function(){
        if(operator_flag===false)
        {
            operator_flag=true;
            operator='+';
        }
    })
    $("#minus").click(function(){
        if(operator_flag===false)
        {
            operator_flag=true;
            operator='-';
        }
    })
    $("#multiply").click(function(){
        if(operator_flag===false)
        {
            operator_flag=true;
            operator='*';
        }
    })
    $("#divide").click(function(){
        if(operator_flag===false)
        {
            operator_flag=true;
            operator='/';
        }
    })
    $("#clickkk").click(function(){
        var result;
        if(operator==='+')
        {
            result=a+b;
        }
        else if(operator==='-')
        {
            result=a-b;
        }
        else if(operator==='*')
        {
            result=a*b;
        }
        else if(operator==='/')
        {
            result=a/b;
        }
        alert(result);
        document.getElementById("special").innerHTML=result;
    })
})